### ISSUE TITLE
Chose output path and file name

### ISSUE THREAD

**Issue by Vifespoir** [madeindjs/Super-Markdown#1]
Hi Alexandre,

First of all, thanks for your amazing Super-Markdown! It works very smoothly! It's a shame that it is hard to find... I'm sure lots of people would be very glad to find it!

It would be great if Super-Markdown could support `-o $PATH/$FILENAME`. So we could decide the filename and the output path.

If you think it's a good idea, I'd be happy to help implement it with your guidance.

Thanks again!

**Comment by madeindjs** [comment]
Bonjour @Vifespoir ,

I'm glad to know you enjoy **Super-Markdown** :) ! 
Of course it will be a great feature. So you can make a pull-request to build it and I will take a look/ accept it.

Thank you very muchfor your help.

**Comment by madeindjs** [comment]
Added in [PR2](https://github.com/madeindjs/Super-Markdown/pull/2), Thank you ;)
